# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "2.1"

services:

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator-0
    entrypoint: settings-tp -vv -C tcp://validator-0:4004

  intkey-tp-python:
    image: hyperledger/sawtooth-intkey-tp-python:1.1
    container_name: sawtooth-intkey-tp-python-default
    depends_on:
      - validator-0
    entrypoint: intkey-tp-python -vv -C tcp://validator-0:4004

  xo-tp-python:
    image: hyperledger/sawtooth-xo-tp-python:1.1
    container_name: sawtooth-xo-tp-python-default
    depends_on:
      - validator-0
    entrypoint: xo-tp-python -vv -C tcp://validator-0:4004

  validator-0:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sawtooth-validator-0-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator-0 with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator-0:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.1
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator-0
    entrypoint: devmode-engine-rust -C tcp://validator-0:5050

  rest-api-0:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-0-default
    ports:
      - "8008:8008"
    depends_on:
      - validator-0
    entrypoint: sawtooth-rest-api -C tcp://validator-0:4004 --bind rest-api-0:8008

  shell:
    image: hyperledger/sawtooth-all:1.1
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api-0
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  mongodb:
    image: "mongo:latest"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"

  healthcare-system-client:
    build:
      context: ../
      dockerfile: docker/client/Dockerfile
    container_name: healthcare-system-client
    expose:
      - 4004
    stop_signal: SIGKILL

  healthcare-system-tp:
    image: hyperledger/healthcare-system-tp
    container_name: healthcare-system-tp
    expose:
      - 4004
    build:
      dockerfile: docker/tp/Dockerfile
      context: ../
    depends_on:
      - validator-0
    entrypoint: /app/main -vv -C tcp://validator-0:4004

volumes:
  mongodb_config:
  mongodb_data: